.\" kylin-user-guide manual page
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.TH KYLIN-USER-GUIDE 1 "26 Feb 2020" "UKUI Desktop Environment"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH "NAME"
kylin-user-guide \- The UKUI Desktop manual
.SH "SYNOPSIS"
.P
This program also accepts the standard GTK options.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/ukui-desktop/kylin-user-guide/issues
.SH "AUTHORS"
.SS kylin-user-guide is maintained by:
.nf
xiaoyiwu <xiaoyiwu@ubuntukylin.com>
.fi
.SS This Man Page has been updated for the UKUI Desktop Environment by:
xiaoyiwu <xiaoyiwu@ubuntukylin.com> (2018)
.SH "SEE ALSO"
.SS Further information may also be available at: http://wiki.ukui-desktop.org/docs
.P
