.\" kylin-user-guide manual page
.\"
.\" Copyright (C) 2020, KylinSoft Co., Ltd.
.\" 
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <https://www.gnu.org/licenses/>.
.\" 
.TH KYLIN-USER-GUIDE 1 "26 Feb 2020" "UKUI Desktop Environment"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH "NAME"
kylin-user-guide \- The UKUI Desktop manual
.SH "SYNOPSIS"
.P
This program also accepts the standard GTK options.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/ubuntukylin/kylin-user-guide/issues
.SH "AUTHORS"
.SS kylin-user-guide is maintained by:
.nf
xiaoyiwu <xiaoyiwu@ubuntukylin.com>
.fi
.SS This Man Page has been updated for the UKUI Desktop Environment by:
xiaoyiwu <xiaoyiwu@ubuntukylin.com> (2020)
.SH "SEE ALSO"
.SS Further information may also be available at:
http://github.com/ubuntukylin/kylin-user-guide
.P
